---
title: "Data Science Capstone"
author: "Ben Tafoya"
date: "February 9, 2021"
output: html_document
---

### Summary

This project represents the Capstone for the Coursera Data Science certification. It is the culmination of a series of courses, built around R Programming that included a mix of courses on programming techniques, accessories, extensions, statistics and applications. This version was built on R-Studio and is presented using their package, Shiny.

The fundamental challenge was to use a very large dataset across multiple files to build a text predicition application. The skills used to complete the project included ...

Downloading text files
Combining files from three sources, potentially across several languages
Cleaning data based typical extraneous items such as whitespace, moving letters to lower case, numbers and articles/prepositions.
Sampling the data to make the application faster
Building an interactive front end in Shiny
Testing the application
Deploying the application on the Shiny server for public view
Completing a short slide deck to summarize



### Successes

The application loads and runs on this site with reasonable speed. 
By adding more records there is a trade-off between the completeness of the text prediciton and the speed of execution of the app.

Some simple phrases are predicted very well ...
User enters "Happy", presses the predict button and the system predicts "birthday"
The user can then add "New" to the phrase and the system will then predict the next word as "year", this without having to resubmit the data using the button, demonstrating the interactive nature of the app.

### Challenges

The application could use the following work to make it beneficial as a backend for a commercial application:

1. Further optimization of speed to accomodate a larger dataset than the existing 7500 records.
2. Further optimization of the N-gram database to increase the strength of the prediction algorithm.
3. Improve the front end to show off capabilities such as timers for search, more attractive colors, longer phrases or multiple predictors.
